coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  native:
    paths:
      - core/
      - src/
    carryforward: false
  frontend:
    paths:
      - app/
    carryforward: false

component_management:
  individual_components:
    - component_id: native
      name: Native
      paths:
        - core/**
        - src/**
    - component_id: frontend
      name: Frontend
      paths:
        - app/**

ignore:
  - build/**
  - test/**
  - tools/**
  - "**/*.d.ts"
