packages:
  - tools/eslint

hoistPattern:
  - "*"

overrides:
  "@electron/node-gyp": 10.2.0-electron.2

onlyBuiltDependencies:
  - electron
  - electron-winstaller

allowBuilds:
  electron: true
  electron-winstaller: true

peerDependencyRules:
  allowedVersions:
    "@electron/fuses": 2.1.3
